In [6]:
#Carregando conjunto de dados
import pandas as pd
arquivo = pd.read_csv(r'C:\Users\kawla\Documents\curso\pandas\wine_dataset.csv')

In [8]:
arquivo.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [9]:
arquivo['style'] = arquivo['style'].replace('red',0)
arquivo['style'] = arquivo['style'].replace('white',1)

In [11]:
arquivo

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,1
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,1
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,1
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,1
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,1

In [12]:
#Separando as variantes entre preditoras e variavel alvo
y = arquivo['style']
x = arquivo.drop('style', axis = 1)

In [18]:
from sklearn.model_selection import train_test_split

#dados teste e treino
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

In [21]:
from sklearn.ensemble import ExtraTreesClassifier
#Criação de modelo:
modelo = ExtraTreesClassifier()
modelo.fit(x_treino,y_treino)

#Imprindo resultado:
resultado = modelo.score(x_teste, y_teste)
print ('Acuracia:', resultado)

Acuracia: 0.9958974358974358

In [22]:
y_teste[400:403]

3377    1
6377    1
3207    1
Name: style, dtype: int64

In [23]:
x_teste[400:403]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
3377,6.4,0.150,0.36,1.8,0.034,43.0,150.0,0.99220,3.42,0.69,11.00,8
6377,5.8,0.315,0.19,19.4,0.031,28.0,106.0,0.99704,2.97,0.40,10.55,6
3207,6.9,0.270,0.49,23.5,0.057,59.0,235.0,1.00240,2.98,0.47,8.60,5

In [24]:
previsoes = modelo.predict(x_teste[400:403])
previsoes

array([1, 1, 1], dtype=int64)